alias nv="watch -n 0.1 nvidia-smi"
alias tmuxa="tmux a -t"
alias tmuxn="tmux new -s"
alias act="conda activate"
alias deact="conda deactivate"
alias setpipthu="pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple"
alias unsetpip="pip config unset global.index-url"
